\defineBarLine "|o" #'("|" #f "|")
\defineBarLine "|-|" #'("|" "|" "|")
\defineBarLine "!-!" #'("!" "!" "!")
\defineBarLine "|" #'("|" "|" "|")
\defineBarLine "||-||" #'("||" "||" "||")
\defineBarLine "||-:|." #'(":|." "||" ".|")
\defineBarLine "||-|." #'("|." "||" ".|")
