\defineBarLine "|-|" #'("|" "|""|")
\defineBarLine "!-!" #'("!" "!""!")
\defineBarLine "|" #'("|" "|""|")
\defineBarLine "||-||" #'("||" "||""||")
\defineBarLine "$" #'("||" "||""||")
\defineBarLine "||-:|." #'(":|." "||" ".|")
\defineBarLine "||-|." #'("|." "||" ".|")
