\defineBarLine "|-|" #'("|" "|" "|")
\defineBarLine "!-!" #'("!" "!" "!")
\defineBarLine "|" #'("|" "|" "|")
\defineBarLine "||-||" #'("||" "||" "||")
\defineBarLine "||-:|." #'(":|." "||" ".|")
\defineBarLine "||-|." #'("|." "||" ".|")
\defineBarLine "|p" #'("|" #f #f)
